apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ template "osg-hosted-ce.name" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "osg-hosted-ce.name" . }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - protocol: TCP
      port: 9619
    {{ if or .Values.Dashboard.Enabled
             ( and (not .Values.HostCredentials.HostCertKeySecret)
                   (not .Values.HostCredentials.HostCertSecret) ) }}
    - protocol: TCP
      port: 80
    {{ end }}
  egress:
  - {}
